"""A 路线物料清单。价格日期 2026-09-12。in_budget=False 的不计入 ¥3200。"""
from __future__ import annotations

from typing import Any, Dict, List

# 来源/预算条目逐项保留；未取得购物车证据，不能将估价视为已核实售价。
ITEMS: List[Dict[str, Any]] = [
    {"sku":"AL-ANGLE-CUT-KIT", "name":"标准角铝下料与钻孔预算", "spec":"按新版实际角铝截面/长度/两面开口模板询价；不采用CNC型腔", "qty":1, "unit_close":80., "unit_retail":160., "in_budget":True, "source":"加工预算上限目标，尚未取得店铺报价", "note":"超出后必须重新算预算；不能把平板激光报价当成角铝裁切报价"},
    {"sku":"SHIPPING-RESERVE", "name":"分店运费预留", "spec":"最终以中国购物车合计替换", "qty":1, "unit_close":40., "unit_retail":60., "in_budget":True, "source":"预算预留，非报价", "note":""},
    {
        "sku": "STS3215-C018",
        "name": "飞特 STS3215 12V 30kg 总线舵机",
        "spec": "12V C018，原厂规格铜齿，磁编码，双轴，55g",
        "qty": 20,
        "unit_close": 90.0,
        "unit_retail": 109.0,
        "in_budget": True,
        "source": "飞特厂家店目标价 / 微雪旗舰零售 ¥109（https://www.waveshare.net/shop/ST3215-Servo.htm）",
        "note": "禁止 7.4V C001。淘宝 ¥99 先核 SKU。G0 必须截图 12V",
    },
    {
        "sku": "Raspberry-Pi-4B-2GB",
        "name": "Raspberry Pi 4B 2GB",
        "spec": "85×56 mm，官方 Φ2.7 安装孔、58×49 孔距",
        "qty": 1,
        "unit_close": 400.0,
        "unit_retail": 450.0,
        "in_budget": True,
        "source": "机械图 datasheets.raspberrypi.com；¥400/450 是预算预留，尚无中国购物车证据",
        "note": "因资料完整优先改选 Pi 4B；需在 G0 锁定中国商家 SKU 和到手价",
    },
    {
        "sku": "WS-BUS-ADAPT-A",
        "name": "微雪总线舵机驱动板 A",
        "spec": "SKU25514，42×33 mm；只作通信接口，舵机电源另行分配",
        "qty": 1,
        "unit_close": 27.0,
        "unit_retail": 27.0,
        "in_budget": True,
        "source": "微雪官网/旗舰 2026-09-12",
        "note": "",
    },
    {
        "sku": "Waveshare-33122-OV2735-A",
        "name": "微雪 OV2735 2MP USB Camera (A)",
        "spec": "25×25 PCB，21×21孔距，Φ14镜头、96°视场；USB SH1.0 4P",
        "qty": 1,
        "unit_close": 79.0,
        "unit_retail": 79.0,
        "in_budget": True,
        "source": "微雪/淘宝工业模组",
        "note": "",
    },
    {
        "sku": "MPU6050",
        "name": "MPU6050 模块",
        "spec": "I2C，后续可换 ICM-42688",
        "qty": 1,
        "unit_close": 8.0,
        "unit_retail": 42.0,
        "in_budget": True,
        "source": "淘宝模块 / ICM-42688 模块 ¥42",
        "note": "零售账用 ICM 价",
    },
    {
        "sku": "USB-MIC",
        "name": "USB 免驱麦克风",
        "spec": "CM6533 类",
        "qty": 1,
        "unit_close": 12.0,
        "unit_retail": 20.0,
        "in_budget": True,
        "source": "淘宝",
        "note": "",
    },
    {
        "sku": "PAM8403-SPK",
        "name": "PAM8403 + 4Ω 3W 腔体喇叭",
        "spec": "5V 供电",
        "qty": 1,
        "unit_close": 15.0,
        "unit_retail": 18.0,
        "in_budget": True,
        "source": "淘宝",
        "note": "",
    },
    {
        "sku": "Gens-Ace-GEA223S25T3GT",
        "name": "格氏 G-Tech 3S 2200mAh 25C 电池",
        "spec": "107×33×22 mm、169 g；原厂多接口适配组件，XT60适配另留空间",
        "qty": 1,
        "unit_close": 95.0,
        "unit_retail": 110.0,
        "in_budget": True,
        "source": "格氏旗舰 2026-09",
        "note": "可加买一只作换电，换电费另计",
    },
    {
        "sku": "DFRobot-DFR0831",
        "name": "DFRobot DFR0831 5V 降压模块",
        "spec": "输入7–24V，5V 0–4A；5A需散热；43.5×20.3×5.5mm；需3A持续热测",
        "qty": 1,
        "unit_close": 20.0,
        "unit_retail": 20.0,
        "in_budget": True,
        "source": "DFRobot中国官网 https://www.dfrobot.com.cn/goods-3061.html；2026-09-13标价¥20",
        "note": "",
    },
    {
        "sku": "PWR-HARNESS",
        "name": "XT60 星形配电 + 硅胶线 + 保险 + 电容",
        "spec": "左腿/右腿/上身三路",
        "qty": 1,
        "unit_close": 55.0,
        "unit_retail": 70.0,
        "in_budget": True,
        "source": "航模店",
        "note": "",
    },
    {
        "sku": "SD-32G",
        "name": "闪迪 32GB 高速 TF",
        "spec": "正品",
        "qty": 1,
        "unit_close": 45.0,
        "unit_retail": 55.0,
        "in_budget": True,
        "source": "京东自营",
        "note": "",
    },
    {
        "sku": "HORN-25T",
        "name": "飞特 25T 金属圆舵盘",
        "spec": "C018 原厂第7页：PCD Φ14 4×M3，主盘总厚4.5，后盘总厚3.1",
        "qty": 20,
        "unit_close": 4.5,
        "unit_retail": 6.0,
        "in_budget": True,
        "source": "飞特配件/淘宝",
        "note": "不可打印",
    },
    {
        "sku": "AL-15-KIT",
        "name": "6061-T6 1.5mm 激光全套",
        "spec": "新开口框架和夹片；按 manufacturing 清单平板下料，无折弯",
        "qty": 1,
        "unit_close": 160.0,
        "unit_retail": 280.0,
        "in_budget": True,
        "source": "淘宝 6061 激光 单件数元，整套估",
        "note": "旧P01–P10图样已废止；下单前按新版逐件DXF询价",
    },
    {
        "sku": "AL-20-FOOT",
        "name": "6061-T6 2.0mm 足板 ×2",
        "spec": "120×70",
        "qty": 1,
        "unit_close": 35.0,
        "unit_retail": 50.0,
        "in_budget": True,
        "source": "同激光店",
        "note": "新版足板有圆角减重窗口，另含颈板、电池托盘；只用新版逐件DXF",
    },
    {
        "sku": "TUBE-20x10x1",
        "name": "6061 矩形管 20×10×1.0",
        "spec": "胸架分段横梁；长度和钻孔按制造清单，不沿用旧12根芯管",
        "qty": 1,
        "unit_close": 28.0,
        "unit_retail": 35.0,
        "in_budget": True,
        "source": "铝管店",
        "note": "",
    },
    {
        "sku": "SCREW-KIT",
        "name": "M2/M2.5/M3内六角、普通六角螺母与隔离柱",
        "spec": "M2/M2.5/M3、M3长夹紧螺栓与螺母；实际数量/长度由逐件清单汇总",
        "qty": 1,
        "unit_close": 50.0,
        "unit_retail": 70.0,
        "in_budget": True,
        "source": "紧固件店",
        "note": "1.5mm 铝禁止攻丝承力",
    },
    {
        "sku": "PETG-1KG",
        "name": "PETG 耗材 1kg",
        "spec": "不透明哑光白，2.4 mm壁；实际切片另核支撑与用料",
        "qty": 1,
        "unit_close": 48.0,
        "unit_retail": 55.0,
        "in_budget": True,
        "source": "拓竹/eSUN 旗舰",
        "note": "",
    },
    {
        "sku": "TPU-05",
        "name": "TPU 95A 0.5kg",
        "spec": "足底 + 线护套",
        "qty": 1,
        "unit_close": 38.0,
        "unit_retail": 45.0,
        "in_budget": True,
        "source": "拓竹/eSUN",
        "note": "",
    },
    {
        "sku": "INSERT-M3",
        "name": "M3 热熔铜螺母",
        "spec": "当前壳体改用捕获螺母/铜柱；本项不采购",
        "qty": 0,
        "unit_close": 15.0,
        "unit_retail": 18.0,
        "in_budget": True,
        "source": "淘宝",
        "note": "",
    },
    {
        "sku": "NYLON",
        "name": "尼龙柱/垫片杂项",
        "spec": "SBC 减振",
        "qty": 1,
        "unit_close": 12.0,
        "unit_retail": 15.0,
        "in_budget": True,
        "source": "淘宝",
        "note": "",
    },
    {
        "sku": "SKYRC-B6NEO",
        "name": "SKYRC B6neo 平衡充",
        "spec": "实验室工具，不计 ¥3200",
        "qty": 1,
        "unit_close": 155.0,
        "unit_retail": 155.0,
        "in_budget": False,
        "source": "航模旗舰",
        "note": "禁止克隆 B6 充比赛电池",
    },
]


def cart(kind: str) -> Dict[str, Any]:
    if kind not in ("close", "retail"):
        raise ValueError(kind)
    key = "unit_close" if kind == "close" else "unit_retail"
    items = []
    total = 0.0
    extra = 0.0
    for raw in ITEMS:
        unit = float(raw[key])
        sub = unit * int(raw["qty"])
        row = dict(raw)
        row["unit_cny"] = unit
        row["subtotal_cny"] = round(sub, 2)
        items.append(row)
        if raw["in_budget"]:
            total += sub
        else:
            extra += sub
    total = round(total, 2)
    return {
        "kind": kind,
        "items": items,
        "total_cny": total,
        "out_of_budget_cny": round(extra, 2),
        "contingency_cny": round(3200.0 - total, 2),
        "budget_cny": 3200.0,
        "price_date": "2026-09-13（除明确官网价外均为待报价预算）",
    }
