"""ATRI-v2 URDF：20 revolute，mm→m、deg→rad。Webots / ROS 入口。

根 link 是 pelvis（站立时世界 Z = profile 的骨盆高度，由仿真器放置）。
网格若存在则用相对路径 meshes/<link>.stl（毫米 STL + scale 0.001）。
独立示意调用可输出包围盒；生产导出要求完整同源网格。Webots导入尚未实测。
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from .assembly3d import kinematic_tree
from .profile import JOINTS, K, MASS, SERVO

MM = 0.001


def _box_inertia(mass: float, sx: float, sy: float, sz: float) -> str:
    ixx = mass * (sy * sy + sz * sz) / 12.0
    iyy = mass * (sx * sx + sz * sz) / 12.0
    izz = mass * (sx * sx + sy * sy) / 12.0
    return (
        f'      <inertia ixx="{ixx:.9f}" ixy="0" ixz="0" '
        f'iyy="{iyy:.9f}" iyz="0" izz="{izz:.9f}"/>'
    )


def _link_box_m(name: str) -> List[float]:
    """碰撞盒（米），大约。"""
    thigh = K["thigh"] * MM
    shank = K["shank"] * MM
    ua = K["upper_arm"] * MM
    fa = K["forearm"] * MM
    if name == "pelvis":
        return [0.090, 0.070, 0.024]
    if name == "torso":
        return [0.100, 0.080, 0.078]
    if "thigh" in name:
        return [0.022, 0.020, thigh]
    if "shank" in name:
        return [0.022, 0.020, shank]
    if "foot" in name:
        return [K["foot_l"] * MM, K["foot_w"] * MM, K["foot_to_ankle_z"] * MM]
    if "upper" in name:
        return [0.020, 0.024, ua]
    if name.endswith("_hand") or name.endswith("_fore"):
        return [0.018, 0.020, fa]
    if "grip" in name:
        return [0.012, 0.020, 0.038]
    if name == "head":
        return [0.056, 0.056, 0.048]
    return [0.030, 0.030, 0.030]


def _link_mass(name: str) -> float:
    total = MASS["design_limit_g"] / 1000.0
    # 粗分：胸腔含电池大脑最重，腿次之。仅给仿真一个可跑的惯性，不是称重。
    w = {
        "pelvis": 0.08,
        "trunk_roll_link": 0.02,
        "torso": 0.22,
        "head_yaw_link": 0.015,
        "head": 0.05,
        "left_hip_roll_link": 0.02,
        "right_hip_roll_link": 0.02,
        "left_thigh": 0.055,
        "right_thigh": 0.055,
        "left_shank": 0.045,
        "right_shank": 0.045,
        "left_foot": 0.04,
        "right_foot": 0.04,
        "left_upper": 0.03,
        "right_upper": 0.03,
        "left_fore": 0.025,
        "right_fore": 0.025,
        "left_hand": 0.015,
        "right_hand": 0.015,
        "left_grip": 0.012,
        "right_grip": 0.012,
    }
    s = sum(w.values())
    return total * w.get(name, 0.01) / s


def _mesh_rel(link: str, mesh_dir: Optional[Path]) -> Optional[str]:
    if mesh_dir is None:
        return None
    p = mesh_dir / f"{link}.stl"
    if p.is_file():
        return f"meshes/{link}.stl"
    return None


def build_urdf(mesh_dir: Optional[Path] = None) -> str:
    tree = kinematic_tree()
    lines: List[str] = [
        '<?xml version="1.0"?>',
        '<robot name="atri_v2">',
        "  <!-- generated by design/v2/urdf.py ; units: mm -> m ; deg -> rad -->",
        "  <!-- REVIEW: inertias and link masses are target-mass allocations, not actual CAD mass properties or measured masses. -->",
        "  <!-- root=pelvis. Spawn with z = pelvis height (see root_xyz_mm). -->",
        f'  <!-- root_xyz_mm="{tree["root_xyz"][0]} {tree["root_xyz"][1]} {tree["root_xyz"][2]}" -->',
        f'  <!-- servo={SERVO["model"]} n={len(JOINTS)} rated_nm={SERVO["rated_nm"]} -->',
    ]
    for lk in tree["links"]:
        name = lk["name"]
        sx, sy, sz = _link_box_m(name)
        mass = _link_mass(name)
        mesh = _mesh_rel(name, mesh_dir)
        lines.append(f'  <link name="{name}">')
        lines.append("    <visual>")
        lines.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append("      <geometry>")
        if mesh:
            lines.append(
                f'        <mesh filename="{mesh}" scale="{MM} {MM} {MM}"/>'
            )
        else:
            lines.append(f'        <box size="{sx:.4f} {sy:.4f} {sz:.4f}"/>')
        lines.append("      </geometry>")
        lines.append("      <material name=\"atri\">")
        lines.append('        <color rgba="0.55 0.62 0.72 1"/>')
        lines.append("      </material>")
        lines.append("    </visual>")
        lines.append("    <collision>")
        lines.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append("      <geometry>")
        lines.append(f'        <box size="{sx:.4f} {sy:.4f} {sz:.4f}"/>')
        lines.append("      </geometry>")
        lines.append("    </collision>")
        lines.append("    <inertial>")
        lines.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        lines.append(f'      <mass value="{mass:.6f}"/>')
        lines.append(_box_inertia(mass, sx, sy, sz))
        lines.append("    </inertial>")
        lines.append("  </link>")

    effort = SERVO["rated_nm"]
    vel = 2 * math.pi * (60.0 / 0.222) / 360.0  # rad/s from 0.222 s/60°
    for j in tree["joints"]:
        xyz = " ".join(f"{v * MM:.6f}" for v in j["xyz"])
        axis = " ".join(str(int(a) if abs(a) in (0.0, 1.0) else a) for a in j["axis"])
        lo, hi = j["limit_deg"]
        lines.append(f'  <joint name="{j["name"]}" type="revolute">')
        lines.append(f'    <parent link="{j["parent"]}"/>')
        lines.append(f'    <child link="{j["child"]}"/>')
        lines.append(f'    <origin xyz="{xyz}" rpy="0 0 0"/>')
        lines.append(f'    <axis xyz="{axis}"/>')
        lines.append(
            f'    <limit lower="{math.radians(lo):.6f}" '
            f'upper="{math.radians(hi):.6f}" '
            f'effort="{effort:.3f}" velocity="{vel:.6f}"/>'
        )
        lines.append("  </joint>")
    lines.append("</robot>")
    return "\n".join(lines) + "\n"


def write_urdf(path: Path, mesh_dir: Optional[Path] = None) -> Dict[str, Any]:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    xml = build_urdf(mesh_dir=mesh_dir)
    path.write_text(xml, encoding="utf-8")
    n = xml.count('type="revolute"')
    return {"path": str(path), "n_revolute": n, "bytes": path.stat().st_size}
